baseURL: http://iagosaito.com
languageCode: en-us
title: iagosaito.com
theme: "PaperMod"

params:

  homeInfoParams: 
    content: Uns artigos aí sobre computação
  socialIcons:
    - name: github
      url: https://github.com/iagosaito

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    # - identifier: archive
    #   name: Archive
    #   url: /archive/
    #   weight: 30